#!/usr/bin/python3

import re
import subprocess
import shlex
import os

import argparse

# Argument Parsing
parser = argparse.ArgumentParser(description="Export all marked TikZ to PNG")
parser.add_argument("filename", help="Path to the LaTex file(s)")
parser.add_argument(
    "-d",
    "--directory",
    default=".",
    type=str,
    help="Directory where the resulting PNGs should be stored",
)

args = parser.parse_args()
export_folder = args.directory
file_name = args.filename


def read_single_file(file_name: str):
    with open(file_name) as f:
        text = f.read()
    return text


text = ""
if os.path.isdir(file_name):
    all_files = os.listdir(file_name)
    for file in all_files:
        if re.match(r"\S+\.tex", file):
            text += read_single_file(f"{file_name}/{file}")
else:
    text = read_single_file(file_name)


# Create export directory, if missing
if not os.path.isdir(export_folder):
    os.mkdir(export_folder)

print("Exported Images:")
images_to_export = re.findall(r"% export (\S+\.png)", text)

for image in images_to_export:
    print(image)
    img_primer = text.find(f"% export {image}")
    img_start = text.find(r"\begin{tikzpicture}", img_primer)
    img_end = text.find(r"\end{tikzpicture}", img_start)

    segment = text[img_start:img_end]

    with open("temp.tex", "w") as f:
        f.write(
            r"""\documentclass{standalone}
\usepackage{graphicx} % Required for inserting images
\usepackage{tikz}

\begin{document}
"""
        )
        f.write(f"{segment}\end{{tikzpicture}}\n\end{{document}}")
    latex_comp = "pdflatex -interaction nonstopmode temp.tex"
    subprocess.check_output(shlex.split(latex_comp))

    pdf_convert = f"magick -density 300 temp.pdf {export_folder}/{image}"
    subprocess.check_output(shlex.split(pdf_convert))

# Clean up temp files

files = os.listdir(".")
for file in files:
    if re.match(r"temp\.\S+", file):
        os.remove(file)
